project:
  type: website

website:
  title: "Kelly Xiao"
  search: false
  sidebar:
    style: docked
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Experience"
        href: experience.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    fontsize: 20pt
    mainfont: "Times New Roman"
    anchor-sections: false
