---
title: "Experience"
---

## Citigroup Inc.

Business Analytics Senior Analyst

- Produced data metrics and analytics for reporting on the progress of 2020 Consent Order Commitments
- Exposed to data Visualization tools such as Tableau and PowerBl
- Assisted with responding lo ad-hoc requests Irom the business, regulators, and management

Internal Audit Analvst

-Provided assistance throughout the audit lifecycle and issue validations
-Assembled PowerPoint decks for informational and training sessions related to audit work
-Understand and effectively utilized the Internal Audit methodology for auditing work

---

## NYC Department of Transportation

Intern

- Conducted site visits to plazas and open streets to follow up on concessions and activations
-Responsible for partners' SAPO (Street Activity Permit Office) applications
-Analvzed data from survevs conducted on open streets throughout the five boroughs in New York Citv

---

## Dollaride

Intern

- Helped conduct ethnographic research on how dollar vans operate along Flatbush route in Brooklyn
- Distributed surveys to van drivers to better understand driver preferences and challenges
- Responsible for pinpointing geographical testing grounds for potential test users
